# Control your input devices
input {
  kb_layout = us
  kb_options = ctrl:nocaps

  repeat_rate = 40
  repeat_delay = 600

  numlock_by_default = true

  touchpad {
    natural_scroll = true
    clickfinger_behavior = true
    scroll_factor = 0.4
  }
}

device {
  name = logitech-mx-vertical-1
  natural_scroll = true
}

# Scroll faster in the terminal
windowrule = scroll_touchpad 1.5, match:class ^(Alacritty|kitty|foot)$
windowrule = scroll_touchpad 0.2, match:class com.mitchellh.ghostty
